/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131315',
        'inverse-surface': '#e4e2e5',
        'surface-container-high': '#292a2c',
        'on-tertiary': '#47290c',
        'secondary-container': '#3394f1',
        'surface-card-alt': '#F5F7FA',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#303033',
        'on-secondary-fixed': '#001c38',
        'primary-fixed-dim': '#b5c7ea',
        'on-primary-fixed-variant': '#364764',
        'on-primary-fixed': '#071c36',
        'on-secondary': '#00315b',
        'tertiary-container': '#321800',
        'on-secondary-container': '#002b50',
        primary: '#b5c7ea',
        'secondary-fixed-dim': '#a2c9ff',
        'on-tertiary-fixed-variant': '#613f20',
        'on-primary': '#1f314d',
        'surface-bright': '#39393b',
        'on-tertiary-container': '#a87e59',
        'border-subtle': '#2C3E50',
        tertiary: '#eebd94',
        'surface-container-low': '#1b1b1e',
        'tertiary-fixed': '#ffdcc1',
        'status-critical': '#E53935',
        'surface-variant': '#343537',
        background: '#131315',
        'surface-container-lowest': '#0d0e10',
        'tertiary-fixed-dim': '#eebd94',
        'error-container': '#93000a',
        'surface-card': '#FFFFFF',
        'status-success': '#43A047',
        'on-surface': '#e4e2e5',
        'surface-dim': '#131315',
        'on-secondary-fixed-variant': '#004881',
        secondary: '#a2c9ff',
        'surface-container-highest': '#343537',
        outline: '#8e9098',
        'primary-fixed': '#d6e3ff',
        'surface-container': '#1f1f22',
        'on-tertiary-fixed': '#2e1500',
        'inverse-primary': '#4d5f7d',
        'secondary-fixed': '#d3e4ff',
        'primary-container': '#0b1f3a',
        error: '#ffb4ab',
        'on-primary-container': '#7587a7',
        'surface-tint': '#b5c7ea',
        'on-surface-variant': '#c4c6ce',
        'outline-variant': '#44474d',
        'on-error': '#690005',
        'status-warning': '#FFB300',
        'on-background': '#e4e2e5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-padding': '24px',
        gutter: '16px',
        'sidebar-width': '260px',
        'sidebar-width-collapsed': '80px',
        'topbar-height': '64px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'title-lg': ['Manrope', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-soft': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(-5%)' },
          '50%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-slow': 'pulse-soft 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce-slow 3s infinite',
      },
    },
  },
  plugins: [],
}
