import Icon from '../ui/Icon.jsx'

const STATUS_STYLES = {
  Complete: 'bg-status-success/20 text-status-success',
  Processing: 'bg-status-warning/20 text-status-warning',
}

export default function ReportsTable({ reports, selectedId, onSelect }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left border-collapse min-w-[640px]">
        <thead className="bg-surface-container-highest/30">
          <tr>
            <th className="p-4 font-label-caps text-label-caps text-on-surface-variant tracking-wider uppercase border-b border-outline-variant">
              Report Type
            </th>
            <th className="p-4 font-label-caps text-label-caps text-on-surface-variant tracking-wider uppercase border-b border-outline-variant">
              Date Generated
            </th>
            <th className="p-4 font-label-caps text-label-caps text-on-surface-variant tracking-wider uppercase border-b border-outline-variant">
              Generated By
            </th>
            <th className="p-4 font-label-caps text-label-caps text-on-surface-variant tracking-wider uppercase border-b border-outline-variant">
              Status
            </th>
            <th className="p-4 border-b border-outline-variant" />
          </tr>
        </thead>
        <tbody className="divide-y divide-outline-variant/30">
          {reports.map((r) => (
            <tr
              key={r.id}
              onClick={() => onSelect(r)}
              className={`group hover:bg-surface-container-high transition-colors cursor-pointer ${
                selectedId === r.id ? 'bg-primary-container/10 border-l-2 border-primary' : ''
              }`}
            >
              <td className="p-4">
                <div className="flex items-center gap-3">
                  <div className={`${r.iconBg} ${r.iconColor} p-2 rounded`}>
                    <Icon name={r.icon} size="20px" />
                  </div>
                  <div>
                    <p className="font-bold text-on-surface">{r.title}</p>
                    <p className="text-on-surface-variant text-[12px]">ID: {r.id}</p>
                  </div>
                </div>
              </td>
              <td className="p-4">
                <p className="text-on-surface font-data-mono">{r.date}</p>
                <p className="text-on-surface-variant text-[12px]">{r.time}</p>
              </td>
              <td className="p-4">
                <div className="flex items-center gap-2">
                  <div
                    className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold ${
                      r.authorHighlight ? 'bg-primary text-on-primary' : 'bg-outline-variant'
                    }`}
                  >
                    {r.authorInitials}
                  </div>
                  <p className="text-on-surface text-body-sm">{r.author}</p>
                </div>
              </td>
              <td className="p-4">
                <span
                  className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[12px] font-bold ${STATUS_STYLES[r.status]}`}
                >
                  <span
                    className={`w-1.5 h-1.5 rounded-full ${
                      r.status === 'Processing' ? 'bg-status-warning animate-pulse' : 'bg-status-success'
                    }`}
                  />
                  {r.status}
                </span>
              </td>
              <td className="p-4 text-right">
                <button className="text-on-surface-variant hover:text-on-surface">
                  <Icon name="more_vert" />
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
